# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XQFlutterHybridDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for XQFlutterHybridDemo

pod 'XQFlutter', :path => '../Flutter/Flutter'
pod 'xq_test_two', :path => '../Flutter/Plugin/xq_test_two'

end
