# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XQHybridFlutterDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for XQHybridFlutterDemo

## Flutter 模块的路径
flutter_application_path = '/Users/wangxingqian/Desktop/Flutter/Flutter学习/Hybrid/xq_hybrid_demo'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')),    binding)





end
